version: '3'

services:
  goapp:
    build: .
    ports:
      - "7070:7070"
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    container_name: mysqlhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productapi
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
