// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Product struct {
	ID            string
	Name          string
	Description   string
	ProductTypeID sql.NullString
	CreatedAt     sql.NullTime
}

type ProductType struct {
	ID          string
	Name        string
	Description string
	CreatedAt   sql.NullTime
}
